# Generated by Django 5.0.7 on 2024-10-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='dislikes',
        ),
    ]
