# Generated by Django 5.0.7 on 2024-10-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_communitypost_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='liked_by',
        ),
    ]
