# Generated by Django 5.1.1 on 2024-10-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_communitypost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
