# Generated by Django 5.0.7 on 2024-10-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkouts',
            name='calories_burned',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
