# Generated by Django 5.0.7 on 2024-10-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
