# Generated by Django 5.0.7 on 2024-10-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_userworkoutplan_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkoutplan',
            name='is_active',
        ),
    ]
