# Generated by Django 5.0.7 on 2024-10-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_userworkoutplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
